### ISSUE TITLE
PUT bug

### ISSUE THREAD

**Issue by 1that** [moevm/mse1h2024-telegram#127]
Нашел баг, что если отправить повторно *PUT* запрос на изменения таблицы, то возникает ошибка 500.
```
2024-04-15 21:09:46 INFO:     10.10.2.1:49274 - "PUT /api/tables/661d6bd78b6bd5af7cadf331?name=111&new_table_id=111&provider=GOOGLE&timer=111 HTTP/1.1" 500 Internal Server Error
2024-04-15 21:09:46 ERROR:    Exception in ASGI application
2024-04-15 21:09:46 Traceback (most recent call last):
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 412, in run_asgi
2024-04-15 21:09:46     result = await app(  # type: ignore[func-returns-value]
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-04-15 21:09:46     return await self.app(scope, receive, send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-04-15 21:09:46     await super().__call__(scope, receive, send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-04-15 21:09:46     await self.middleware_stack(scope, receive, send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-04-15 21:09:46     raise exc
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-04-15 21:09:46     await self.app(scope, receive, _send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024-04-15 21:09:46     await self.simple_response(scope, receive, send, request_headers=headers)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024-04-15 21:09:46     await self.app(scope, receive, send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
2024-04-15 21:09:46     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-15 21:09:46     raise exc
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-15 21:09:46     await app(scope, receive, sender)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
2024-04-15 21:09:46     await self.middleware_stack(scope, receive, send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
2024-04-15 21:09:46     await route.handle(scope, receive, send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
2024-04-15 21:09:46     await self.app(scope, receive, send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
2024-04-15 21:09:46     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-04-15 21:09:46     raise exc
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-04-15 21:09:46     await app(scope, receive, sender)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
2024-04-15 21:09:46     response = await func(request)
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
2024-04-15 21:09:46     raw_response = await run_endpoint_function(
2024-04-15 21:09:46   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-04-15 21:09:46     return await dependant.call(**values)
2024-04-15 21:09:46   File "/backend/app/routers/crud.py", line 168, in edit_table
2024-04-15 21:09:46     TablesManager().update_table(table)
2024-04-15 21:09:46   File "/backend/app/tables/tables_manager.py", line 37, in update_table
2024-04-15 21:09:46     self.delete_table(table.table_id)
2024-04-15 21:09:46   File "/backend/app/tables/tables_manager.py", line 44, in delete_table
2024-04-15 21:09:46     task = self.__tables.pop(table_id)
2024-04-15 21:09:46 KeyError: '111'
```

**Comment by D1mitrii** [comment]
В классе **TableManager** не правильно хранятся воркеры таблицы. В словаре ___tables_ ключом является _url_ на онлайн-таблицу, а не _id_ из базы. В результате изменения _url_, ключ не находится и мы получаем **runtime** ошибку.
